[FUSION-15] removed tvOS example project and documentation
janrain/AppAuth-iOS pull request #8
Opened 2022-10-25 20:46 UTC by akamimoor

## JIRA ticket
[FUSION-15](https://janrain.atlassian.net/browse/FUSION-15)

## Changes

- Removed the tvOS sample app
- Removed the tvOS documentation

Confluence doc for development instructions: [Here](https://janrain.atlassian.net/l/cp/wqc2506v)

2022-10-26 00:39 UTC, kreese-akamai submitted a review, later dismissed
Also, needs some changes in `.github/workflows/tests.yml`
see: https://github.com/janrain/AppAuth-iOS/pull/10/files

2022-10-26 00:39 UTC, kreese-akamai commented on Package.swift
> +        )
```suggestion
        ),
```

2022-10-26 14:10 UTC, schaeferCode approved these changes
Seems pretty good. I'm good with the changes assuming @kreese-akamai 's comments are addressed.

2022-10-26 14:32 UTC, akamimoor commented
Looks good to me!

2022-10-28 23:39 UTC, AnyaDKing commented on Package.swift
> -            exclude: ["OIDSwiftTests.swift", "AppAuthTV"]
Should this be removed entirely, or just the `AppAuthTv` portion?

2022-10-28 23:39 UTC, AnyaDKing commented on .github/workflows/tests.yml
> +    runs-on: macOS-11
Was this for testing? Or should this be changed?

2022-10-29 00:33 UTC, kreese-akamai commented on .github/workflows/tests.yml
> +    runs-on: macOS-11
GitHub released testing image `macOS-12` recently _(this past week)_. Previously `macOS-latest` was spinning up an instance of `macOS-11`, but now `macOS-latest` runs `macOS-12`. For one reason or another, the AppAuth test suite is not compatible without additional changes. This is apparent in [master branch commit history](https://github.com/janrain/AppAuth-iOS/commits/master), where no code changes occur other than clean merges. You can also see which unit tests pass and fail in this [testing branch](https://github.com/janrain/AppAuth-iOS/pull/10) clicking on the red **x** by each commit sha.

2022-10-29 00:35 UTC, kreese-akamai commented on .github/workflows/tests.yml
> +    runs-on: macOS-11
We are also several commits behind the upstream [openid/AppAuth-iOS)](https://github.com/openid/AppAuth-iOS) repo off which we are forked. They will likely need to update their GitHub workflows and/or test suites to support `macOS-12`. That may be a good time for us to merge in their master branch into our master branch.

2022-10-29 01:07 UTC, kreese-akamai requested changes
proposed changes in [Test Pull Request](https://github.com/janrain/AppAuth-iOS/pull/10/file)

2022-10-29 01:07 UTC, kreese-akamai commented on Package.swift
> -            exclude: ["OIDSwiftTests.swift", "AppAuthTV"]
Good catch! This should be restored:
```swift
.testTarget(
    name: "AppAuthCoreTests",
    dependencies: ["AppAuthCore"],
    path: "UnitTests",
    exclude: ["OIDSwiftTests.swift"]
),
```
Verified with [Test Commit](https://github.com/janrain/AppAuth-iOS/pull/10/commits/ef0d11fae30bb4e4413b61223e7b63116bbd2cb3)

2022-11-04 21:49 UTC, jbush-janrain approved these changes

2022-11-04 21:49 UTC, merged